@startuml mascota 

class Mascota
{
    -emocion:Emocion
    +Comer(Alimento)
    +Beber(Agua)
    +Jugar(Juguete)
    +Poner(Accesorio)

}

class Alimento
{
    -carne:Carne
    -galleta:Galleta
    -verdura:Verdura
    -fruta:Fruta
}
class Juguete
{
    -frisbee:Frisbee
    -pelota:Pelota
    -peluche:Peluche
}

class Accesorio
{
    -sombrero:Sombrero
    -moño:Moño
    -collar:Collar
    -ropa:Ropa
}

class Emocion
{
    -desagrado:Desagrado
    -enojo:Enojo
    -tristeza:Tristeza
    -felicidad:Felicidad
}

package Emociones
{
    Class Felicidad
    Class Tristeza 
    Class Enojo
    Class Desagrado
}

package Alimentos
{
    Class Fruta
    Class Verdura
    class Galleta
    class Carne
}

package Juguetes
{
    class Peluche
    class Pelota
    class Frisbee
}

package Accesorios
{
    class Ropa
    class Collar
    class Moño
    class Sombrero
}

Package Ropas
{
    Class Pantalon 
    Class Sueter 
}

class Agua

Alimento "*"--o "1" Mascota
Mascota "1" o-- "3" Juguete
Carne--|>Alimento
Pelota--|>Juguete

Pantalon--|>Ropa 
Sueter--|>Ropa 
Galleta--|>Alimento
Fruta--|>Alimento
Verdura--|>Alimento
Ropa--|>Accesorio
Accesorio "5"--o "1" Mascota
Emocion "*"--*"1" Mascota
Enojo--|>Emocion
Tristeza--|>Emocion
Felicidad--|>Emocion
Desagrado--|>Emocion
Collar--|>Accesorio
Moño--|>Accesorio
Sombrero--|>Accesorio
Peluche--|>Juguete
Frisbee--|>Juguete
Mascota "1" o--"*" Agua

@enduml